# Generated by Django 4.2.14 on 2024-08-06 01:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_remove_banner_percentage_remove_product_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Review',
        ),
    ]
