# Generated by Django 4.2.14 on 2024-08-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_rate_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
